apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l2ti3fl2n-java-quarkus
  janus-idp.io/tekton: l2ti3fl2n-java-quarkus
  backstage.io/kubernetes-id: l2ti3fl2n-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l2ti3fl2n-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
